# Generated by Django 5.2 on 2025-04-05 21:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alunos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="avaliacao",
            name="faltas",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
