# Generated by Django 5.2.6 on 2025-10-04 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alunos", "0002_alter_avaliacao_faltas"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aluno",
            name="matricula",
            field=models.CharField(
                error_messages={
                    "unique": "Matrícula já cadastrada. Use uma diferente."
                },
                max_length=20,
                unique=True,
            ),
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto", models.TextField()),
                ("visivel_para_aluno", models.BooleanField(default=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to="alunos.aluno",
                    ),
                ),
                (
                    "professor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feedbacks",
                        to="alunos.professor",
                    ),
                ),
            ],
            options={
                "ordering": ["-criado_em"],
                "indexes": [
                    models.Index(
                        fields=["aluno", "-criado_em"],
                        name="alunos_feed_aluno_i_f7c7ec_idx",
                    )
                ],
            },
        ),
    ]
