# Generated by Django 5.0.6 on 2025-10-24 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0004_disciplina'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='disciplinas',
            field=models.ManyToManyField(blank=True, related_name='alunos', to='alunos.disciplina'),
        ),
    ]
