[pytest]
DJANGO_SETTINGS_MODULE = escola.settings_test

python_files = test_*.py *_test.py
python_classes = Test*
python_functions = test_*

django_find_project = true

testpaths =
    alunos/test

addopts =
    --ignore=alunos/test/test_RN.py
    --disable-warnings
    --maxfail=1
    -p no:faulthandler
    -p no:locust

